In [1]:
! python ../strkernels/compile_core.py

Compiling str_kernel.c...
Compiling locality_improved_sk.c...
Compiling str_kernel_matrix.c...
Compiling sqrt_diag_normalizer.c...
Compiling subsequence_sk.c...
Compiling fixed_degree_sk.c...
Compiling spectrum_sk.c...
Compiling normalizer.c...
Compiling weighted_degree_sk.c...
Linking object files...
Compilation completed successfully!


In [2]:
import numpy as np
from sys import path
path.append('..')

from strkernels import SpectrumStringKernel

order == 1

In [3]:
# No normalization
spectrum_kernel = SpectrumStringKernel(normalizer=None, 
                                       order=1, 
                                       alphabet=0)

strings = np.array(["ATCG", "ATGG", "TACG", "GCTA"])
kernel_matrix = spectrum_kernel(strings, strings)
print(kernel_matrix)

[[4. 4. 4. 4.]
 [4. 6. 4. 4.]
 [4. 4. 4. 4.]
 [4. 4. 4. 4.]]


In [4]:
strings1 = np.array(["ATCG", "ATGG"])
strings2 = np.array(["ATCG", "GGGG", "CCCC"])
kernel_matrix = spectrum_kernel(strings1, strings2)
print('\n', kernel_matrix)


 [[4. 4. 4.]
 [4. 8. 0.]]


In [5]:
# Wiht standard normalization (srqt diagonal)
spectrum_kernel = SpectrumStringKernel(order=1, 
                                       alphabet=0)

strings = np.array(["ATCG", "ATGG", "TACG", "GCTA"])
kernel_matrix = spectrum_kernel(strings, strings)
print(kernel_matrix)

[[1.         0.81649658 1.         1.        ]
 [0.81649658 1.         0.81649658 0.81649658]
 [1.         0.81649658 1.         1.        ]
 [1.         0.81649658 1.         1.        ]]


In [6]:
strings1 = np.array(["ATCG", "ATGG"])
strings2 = np.array(["ATCG", "GGGG", "CCCC"])
kernel_matrix = spectrum_kernel(strings1, strings2)
print('\n', kernel_matrix)


 [[1.         0.5        0.5       ]
 [0.81649658 0.81649658 0.        ]]


order == 3

In [7]:
# No normalization
spectrum_kernel = SpectrumStringKernel(normalizer=None, 
                                       order=3, 
                                       alphabet=0)

strings = np.array(["ATCG", "ATGG", "TACG", "GCTA"])
kernel_matrix = spectrum_kernel(strings, strings)
print(kernel_matrix)

[[ 9.  5.  5.  4.]
 [ 5. 11.  4.  4.]
 [ 5.  4.  9.  5.]
 [ 4.  4.  5.  9.]]


In [8]:
strings1 = np.array(["ATCG", "ATGG"])
strings2 = np.array(["ATCG", "GGGG", "CCCC"])
kernel_matrix = spectrum_kernel(strings1, strings2)
print('\n', kernel_matrix)


 [[ 9.  4.  4.]
 [ 5. 11.  0.]]


In [9]:
# Wiht standard normalization (srqt diagonal)
spectrum_kernel = SpectrumStringKernel(order=3, 
                                       alphabet=0)

strings = np.array(["ATCG", "ATGG", "TACG", "GCTA"])
kernel_matrix = spectrum_kernel(strings, strings)
print(kernel_matrix)

[[1.         0.50251891 0.55555556 0.44444444]
 [0.50251891 1.         0.40201513 0.40201513]
 [0.55555556 0.40201513 1.         0.55555556]
 [0.44444444 0.40201513 0.55555556 1.        ]]


In [10]:
strings1 = np.array(["ATCG", "ATGG"])
strings2 = np.array(["ATCG", "GGGG", "CCCC"])
kernel_matrix = spectrum_kernel(strings1, strings2)
print('\n', kernel_matrix)


 [[1.         0.24759378 0.24759378]
 [0.50251891 0.61588176 0.        ]]
